version: '3'
services:
 app:
    build: .
    image: spring-app
    ports:
      - "9798:9798"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/biblio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw

 mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: biblio
    ports:
      - "3306:3306"

 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9499:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: my-secret-pw
    depends_on:
      - mysql
