spring:
 datasource:
    url: jdbc:mysql://localhost:3306/bi
    username: root
    password: ""
 jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop