server:
  port: 9897

# Configuration de la base de données MySQL
spring:
  #profiles:
    #active: test
  datasource:
    url: jdbc:mysql://localhost:3306/biblio
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/,classpath:/static/images/,classpath:/static/css/,classpath:/static/js/,classpath:/static/vendors/,classpath:/static/uploads/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB   
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

