spring:
 datasource:
    
    url: jdbc:mysql://localhost:3306/biblio_dev
    username: dev_user
    password: dev_password
 jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
